apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-k8sappswd-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app-k8sappswd-deployment
  template:
    metadata:
      labels:
        app: demo-app-k8sappswd-deployment
    spec:
      containers:
        - name: demo-container-k8sappswd
          image: tuouser/k8sappswd:latest  # Sostituisci 'tuouser' con il tuo username Docker Hub
          imagePullPolicy: IfNotPresent  # Use IfNotPresent to avoid pulling the image if it already exists
          ports:
          - containerPort: 5000
            protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"