apiVersion: v1
kind: Pod
metadata:
  name: demo-k8appswd
  labels:
    app.kubernetes.io/name: demo-k8appswd
spec:
  containers:
  - name: demo-k8appswd-container
    image: k8sappswd:v1
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8080
      protocol: TCP
